/* ═══════════════════════════════════════════════════════════════
   ONYX Worker — email (Resend) + lean contact enrichment (OpenAI)
   ═══════════════════════════════════════════════════════════════
   POST { action: "email",  ... } → Resend
   POST { action: "enrich", ... } → OpenAI web search

   Enrichment intentionally returns ONLY:
     { name, phone, email, sources }

   Token controls:
   - very small research prompt
   - only essential lead facts are sent to OpenAI
   - low web-search context
   - max 3 built-in tool calls
   - strict 3-field model output schema
   - source URLs are extracted from tool results, not generated by the model
   - max_output_tokens prevents runaway output
   ═══════════════════════════════════════════════════════════════ */

const ALLOWED_ORIGINS = [
  'https://onyx.edgeform-media.com',
  'https://crm.edgeform-media.com',
  'http://localhost:8080',
  'http://127.0.0.1:8080'
];

const SEND_DOMAIN = 'edgeform-media.com';
const DAILY_CAP = 400;

export default {
  async fetch(request, env) {
    const origin = request.headers.get('Origin') || '';
    const cors = corsHeaders(origin);

    if (request.method === 'OPTIONS') return new Response(null, { headers: cors });
    if (request.method !== 'POST') return json({ ok: false, error: 'POST only' }, 405, cors);

    let body;
    try {
      body = await request.json();
    } catch (e) {
      return json({ ok: false, error: 'Body must be JSON.' }, 400, cors);
    }

    if (!env.ONYX_SECRET || body.secret !== env.ONYX_SECRET) {
      return json({ ok: false, error: 'Unauthorized.' }, 401, cors);
    }

    try {
      if (body.action === 'ping') return json({ ok: true, service: 'onyx-worker' }, 200, cors);
      if (body.action === 'email') return json(await sendEmail(body, env), 200, cors);
      if (body.action === 'enrich') return json(await enrich(body, env), 200, cors);
      return json({ ok: false, error: 'Unknown action: ' + body.action }, 400, cors);
    } catch (err) {
      return json({ ok: false, error: String((err && err.message) || err) }, 500, cors);
    }
  }
};

/* ── helpers ─────────────────────────────────────────────────── */

function corsHeaders(origin) {
  const allow = ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0];
  return {
    'Access-Control-Allow-Origin': allow,
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Vary': 'Origin'
  };
}

function json(data, status, cors) {
  return new Response(JSON.stringify(data), {
    status: status || 200,
    headers: Object.assign({ 'Content-Type': 'application/json' }, cors || {})
  });
}

/* ── email ───────────────────────────────────────────────────── */

async function sendEmail(body, env) {
  const to = String(body.to || '').trim();
  const subject = String(body.subject || '').trim();
  const html = String(body.html || body.htmlBody || '').trim();
  const text = String(body.text || body.body || '').trim();

  if (!to || !/^[^@\s]+@[^@\s]+\.[a-z]{2,}$/i.test(to)) {
    return { ok: false, error: 'Bad "to" address.' };
  }
  if (!subject) return { ok: false, error: 'Subject is required.' };
  if (!html && !text) return { ok: false, error: 'Message body is empty.' };

  const localPart = String(body.fromLocal || 'email')
    .toLowerCase()
    .replace(/[^a-z0-9._-]/g, '');
  const fromName = String(body.fromName || 'Edgeform Media')
    .replace(/["<>\r\n]/g, '')
    .slice(0, 60);

  const from = `${fromName} <${localPart || 'email'}@${SEND_DOMAIN}>`;
  const replyTo = /@/.test(body.replyTo || '')
    ? body.replyTo
    : `${localPart || 'email'}@${SEND_DOMAIN}`;

  if (env.ONYX_KV) {
    const key = 'sent:' + new Date().toISOString().slice(0, 10);
    const used = parseInt((await env.ONYX_KV.get(key)) || '0', 10);
    if (used >= DAILY_CAP) {
      return { ok: false, error: `Daily cap of ${DAILY_CAP} reached.` };
    }
    await env.ONYX_KV.put(key, String(used + 1), { expirationTtl: 172800 });
  }

  const payload = { from, to: [to], subject, reply_to: replyTo };
  if (html) payload.html = html;
  if (text) payload.text = text;

  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${env.RESEND_API_KEY}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(payload)
  });

  const result = await res.json();
  if (!res.ok) {
    return {
      ok: false,
      error: result.message || 'Resend rejected the message.',
      details: result
    };
  }

  return { ok: true, id: result.id, to, from, subject };
}

/* ── lean contact enrichment ─────────────────────────────────── */

const ENRICH_SYSTEM = `Find the person who controls purchasing for this business (prefer owner/founder, then medical director or practice manager) and their public contact info. Use web search. Do not guess names, phone numbers, or emails; no pattern-derived emails. Prefer a direct phone, otherwise use the public business phone. If a field cannot be verified, return an empty string.`;

const CONTACT_SCHEMA = {
  type: 'object',
  properties: {
    name: { type: 'string' },
    phone: { type: 'string' },
    email: { type: 'string' }
  },
  required: ['name', 'phone', 'email'],
  additionalProperties: false
};

async function enrich(body, env) {
  const lead = body.lead || {};
  const name = String(lead.name || '').trim();

  if (!name) return { ok: false, error: 'Lead needs at least a business name.' };

  // Only send identifying facts that materially help web search.
  // Intentionally ignore ratings, lead score, buyer type, maps URL, etc.
  const location = [lead.city, lead.state].filter(Boolean).join(', ');
  const facts = [
    `Business: ${name}`,
    lead.website ? `Website: ${String(lead.website).trim()}` : '',
    location ? `Location: ${location}` : '',
    lead.phone ? `Known business phone: ${String(lead.phone).trim()}` : ''
  ].filter(Boolean).join('\n');

  const res = await fetch('https://api.openai.com/v1/responses', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${env.OPENAI_API_KEY}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model: body.model || 'gpt-4.1',

      // Keep retrieved search context small and stop excessive searching.
      tools: [{ type: 'web_search_preview', search_context_size: 'low' }],
      max_tool_calls: 3,

      // Hard ceiling on generated tokens. The actual JSON is usually far smaller.
      max_output_tokens: 250,

      // Force tiny predictable output instead of asking the model to format 20+ fields.
      text: {
        format: {
          type: 'json_schema',
          name: 'contact_lookup',
          strict: true,
          schema: CONTACT_SCHEMA
        }
      },

      input: [
        { role: 'system', content: ENRICH_SYSTEM },
        { role: 'user', content: facts }
      ]
    })
  });

  const data = await res.json();
  if (!res.ok) {
    return {
      ok: false,
      error: (data.error && data.error.message) || 'OpenAI rejected the request.'
    };
  }

  const parsed = parseJson(extractText(data));
  if (!parsed) {
    return { ok: false, error: 'Could not parse the model output.' };
  }

  // Sources come from OpenAI's web-search result metadata, so the model does not
  // spend output tokens copying URLs into its JSON response.
  const sources = extractSources(data);

  return {
    ok: true,
    data: {
      name: cleanValue(parsed.name),
      phone: cleanValue(parsed.phone),
      email: cleanValue(parsed.email),
      sources,
      enrichedAt: new Date().toISOString()
    }
  };
}

function cleanValue(value) {
  const s = String(value || '').trim();
  return /^unknown$/i.test(s) ? '' : s;
}

function extractText(data) {
  if (typeof data.output_text === 'string' && data.output_text) {
    return data.output_text;
  }

  let out = '';
  for (const item of data.output || []) {
    for (const c of item.content || []) {
      if (typeof c.text === 'string') out += c.text;
    }
  }
  return out;
}

function extractSources(data) {
  const urls = [];
  const add = (url) => {
    const u = String(url || '').trim();
    if (/^https?:\/\//i.test(u) && !urls.includes(u)) urls.push(u);
  };

  for (const item of data.output || []) {
    if (item.type === 'web_search_call') {
      const action = item.action || {};

      // Search calls can expose every source used by that search.
      for (const source of action.sources || []) add(source && source.url);

      // Open/find actions can expose a page URL directly.
      add(action.url);
    }

    // Fallback: collect URL citations attached to output text.
    for (const c of item.content || []) {
      for (const annotation of c.annotations || []) {
        if (annotation && annotation.type === 'url_citation') add(annotation.url);
      }
    }
  }

  return urls.slice(0, 6);
}

function parseJson(text) {
  const cleaned = String(text || '').replace(/```json|```/g, '').trim();
  try {
    return JSON.parse(cleaned);
  } catch (e) {
    return null;
  }
}
