(function () {
  'use strict';
  const LH3 = window.LH3, K_SET='lh3_settings', K_LEADS='lh3_leads', K_HISTORY='lh3_research_history', K_SEEN='lh3_seen', K_RUN='lh3_run';
  const $=id=>document.getElementById(id), get=async(k,d)=>{const x=await chrome.storage.local.get(k);return x[k]===undefined?d:x[k];};
  let S;
  const save=()=>chrome.storage.local.set({[K_SET]:S});
  const msg=(text,kind)=>{const e=$('msg');e.textContent=text||'';e.className='msg '+(kind||'');};
  const fmt=n=>Number(n||0).toLocaleString('en-US');
  function chips(key,id){const root=$(id);root.textContent='';(S[key]||[]).forEach((value,i)=>{const li=document.createElement('li'),label=document.createElement('span'),remove=document.createElement('button');label.textContent=value;remove.textContent='×';remove.title='Remove';remove.onclick=()=>{S[key].splice(i,1);save();chips(key,id);summary();};li.append(label,remove);root.append(li);});}
  function summary(){ $('sumTerms').textContent=fmt((S.terms||[]).length);$('sumCities').textContent=fmt((S.cities||[]).length); }
  async function counts(){ $('leadCount').textContent=fmt((await get(K_LEADS,[])).length); }
  async function activeTab(){return (await chrome.tabs.query({active:true,currentWindow:true}))[0];}
  async function send(type){const tab=await activeTab();if(!tab||!/^https:\/\/www\.google\.com\/(maps|search)/.test(tab.url||'')){msg('Open Google Maps first.','warn');return null;}try{return await chrome.tabs.sendMessage(tab.id,{type});}catch{msg('Reload Google Maps once, then try again.','warn');return null;}}
  async function refresh(){const tab=await activeTab(),run=await get(K_RUN,null),maps=/^https:\/\/www\.google\.com\/maps/.test((tab||{}).url||'');$('start').hidden=!!(run&&run.active);$('stop').hidden=!(run&&run.active);$('scan').disabled=!maps;$('pill').textContent=run&&run.active?'Scraping':maps?'Ready':'Open Maps';$('pill').className='pill '+(run&&run.active?'live':maps?'':'off');$('where').textContent=run&&run.active?'Scraping Google Maps — leave the tab open.':maps?'Ready to find laser hair removal opportunities.':'Open Google Maps to scrape leads.';}
  async function research(){const leads=await get(K_LEADS,[]),min=Number(S.minRating||0),max=Number(S.maxRating||5),hits=leads.filter(l=>Number(l.rating)>=min&&Number(l.rating)<=max).sort((a,b)=>Number(a.rating)-Number(b.rating)||Number(b.reviewCount)-Number(a.reviewCount));$('researchPanel').hidden=false;$('researchCount').textContent=`${fmt(hits.length)} saved businesses in the ${min}–${max} star range, worst first.`;const root=$('researchResults');root.textContent='';if(!hits.length){root.textContent='No saved leads match this range yet.';return;}hits.slice(0,50).forEach(l=>{const row=document.createElement('div'),title=document.createElement('b'),meta=document.createElement('span'),open=document.createElement('button');row.className='research-result';title.textContent=`${l.rating} ★  ${l.name||'Unnamed business'}`;meta.textContent=`${[l.city,l.state].filter(Boolean).join(', ')} · ${l.reviewCount||0} reviews`;open.className='btn quiet compact';open.textContent='Open Maps reviews';open.onclick=()=>chrome.tabs.create({url:l.mapsUrl||('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent([l.name,l.city,l.state].filter(Boolean).join(' ')))});row.append(title,meta,open);root.append(row);});}
  function ratingButtons(){document.querySelectorAll('[data-min]').forEach(btn=>btn.onclick=()=>{S.minRating=Number(btn.dataset.min);S.maxRating=Number(btn.dataset.max);S.badReviewMode=true;$('badReviewMode').checked=true;$('ratingControls').hidden=false;save();research();});}
  async function init(){S=Object.assign({},LH3.DEFAULT_SETTINGS,await get(K_SET,{}),{sheetUrl:LH3.DEFAULT_SETTINGS.sheetUrl,sheetSecret:LH3.DEFAULT_SETTINGS.sheetSecret,syncToSheet:true});if(!Array.isArray(S.terms))S.terms=[...LH3.DEFAULT_SETTINGS.terms];if(!Array.isArray(S.cities))S.cities=[...LH3.DEFAULT_SETTINGS.cities];save();chips('terms','termList');chips('cities','cityList');summary();counts();['limit','pagesPerQuery','minDelayMs','maxDelayMs'].forEach(id=>{$(id).value=S[id];$(id).onchange=()=>{S[id]=Math.max(1,Number($(id).value)||1);save();summary();};});['requirePhone','skipChains','skipSeen'].forEach(id=>{$(id).checked=!!S[id];$(id).onchange=()=>{S[id]=$(id).checked;save();};});$('badReviewMode').checked=!!S.badReviewMode;$('ratingControls').hidden=!S.badReviewMode;$('badReviewMode').onchange=()=>{S.badReviewMode=$('badReviewMode').checked;$('ratingControls').hidden=!S.badReviewMode;save();};ratingButtons();$('addTerm').onclick=()=>{const v=$('termInput').value.trim().toLowerCase();if(v&&!S.terms.includes(v)){S.terms.push(v);save();chips('terms','termList');summary();}$('termInput').value='';};$('addCity').onclick=()=>{const v=$('cityInput').value.trim();if(v&&!S.cities.includes(v)){S.cities.push(v);save();chips('cities','cityList');summary();}$('cityInput').value='';};$('start').onclick=async()=>{const r=await send('LH3_START');if(r&&r.ok)msg(`Scraping ${r.steps} searches directly into ONYX.`,'good');else if(r)msg(r.error,'warn');refresh();};$('stop').onclick=async()=>{await send('LH3_STOP');msg('Scrape stopped. Leads already found are saved in ONYX.','good');refresh();};$('scan').onclick=async()=>{const r=await send('LH3_SCAN');if(r)msg('Scanned this Maps page.','good');counts();};$('research').onclick=research;$('openSearch').onclick=()=>chrome.tabs.create({url:'https://www.google.com/maps'});await refresh();setInterval(()=>{refresh();counts();},2000);}
  init();
})();
